package turing.mods.polaris.registry;

import net.minecraft.util.ResourceLocation;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fluids.FluidAttributes;
import turing.mods.polaris.Polaris;

import java.util.HashMap;

public class FluidRegistry {
    private static final ResourceLocation TEXTURE = Polaris.modLoc("block/fluids/autogenerated");
    private static final FluidDeferredRegister FLUID_DEFERRED_REGISTER = new FluidDeferredRegister();

    public static final BasicFluidRegistryObject STEAM = register("steam",
            FluidAttributes.builder(TEXTURE, TEXTURE).gaseous().temperature(1800).color(0xFFAAAAAA)
    );

    public static void register(IEventBus bus) {
        FLUID_DEFERRED_REGISTER.register(bus);
    }

    public static void registerDispenseBehavior() {
        FLUID_DEFERRED_REGISTER.registerBucketDispenseBehavior();
    }

    public static BasicFluidRegistryObject register(String name, FluidAttributes.Builder builder) {
        return FLUID_DEFERRED_REGISTER.register(name, builder);
    }

    public static HashMap<String, FluidRegistryObject<?, ?, ?, ?>> getFluids() {
        return FLUID_DEFERRED_REGISTER.getFluids();
    }
}
