package turing.mods.polaris.registry;

import mcp.MethodsReturnNonnullByDefault;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fluids.FluidAttributes;
import turing.mods.polaris.Polaris;
import turing.mods.polaris.material.Material;

import javax.annotation.ParametersAreNonnullByDefault;
import java.util.HashMap;
import java.util.function.Supplier;

@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
public class FluidRegistry {
    private static final ResourceLocation TEXTURE = Polaris.modLoc("block/fluids/autogenerated");
    private static final FluidDeferredRegister FLUID_DEFERRED_REGISTER = new FluidDeferredRegister();

    public static void register(IEventBus bus) {
        FLUID_DEFERRED_REGISTER.register(bus);
    }

    public static void registerDispenseBehavior() {
        FLUID_DEFERRED_REGISTER.registerBucketDispenseBehavior();
    }

    public static BasicFluidRegistryObject register(String name, FluidAttributes.Builder builder, Supplier<Material> materialSupplier) {
        return FLUID_DEFERRED_REGISTER.register(name, builder, materialSupplier);
    }

    public static BasicFluidRegistryObject register(String name, FluidAttributes.Builder builder) {
        return FLUID_DEFERRED_REGISTER.register(name, builder);
    }

    public static HashMap<String, FluidRegistryObject<?, ?, ?, ?>> getFluids() {
        return FLUID_DEFERRED_REGISTER.getFluids();
    }
}
