package turing.mods.polaris.registry;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fluids.FluidAttributes;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import turing.mods.polaris.Polaris;
import turing.mods.polaris.item.SubItemGenerated;
import turing.mods.polaris.material.MaterialBuilder;
import turing.mods.polaris.material.SubItem;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class MaterialDeferredRegister {
    public static final HashMap<String, MaterialRegistryObject> materials = new HashMap<>();
    private final DeferredRegister<Item> itemRegister;
    private final DeferredRegister<Block> blockRegister;
    private static final ResourceLocation TEXTURE = Polaris.modLoc("block/fluids/autogenerated");

    public MaterialDeferredRegister() {
        itemRegister = DeferredRegister.create(ForgeRegistries.ITEMS, Polaris.MODID);
        blockRegister = DeferredRegister.create(ForgeRegistries.BLOCKS, Polaris.MODID);
    }

    public HashMap<String, MaterialRegistryObject> getMaterials() {
        return materials;
    }

    public MaterialRegistryObject register(String name, MaterialBuilder builder) {
        BasicFluidRegistryObject fluid = null;
        List<RegistryObject<Block>> blocks = new ArrayList<>();
        List<RegistryObject<Item>> items = new ArrayList<>();
        if (builder.fluidStats != null) {
            FluidAttributes.Builder attributes = FluidAttributes.builder(TEXTURE, TEXTURE).color(builder.color).temperature(builder.fluidStats.temp).translationKey("material.polaris." + name);
            if (builder.fluidStats.isGaseous()) attributes.gaseous();
            fluid = FluidRegistry.register(name, attributes);
        }
        if (builder.oreStats != null && builder.existingItems.stream().noneMatch(item -> item.getRegistryName().getPath().contains("ore"))) ;
        if (builder.subItems.contains(SubItem.BLOCK) && builder.existingItems.stream().noneMatch(item -> item.getRegistryName().getPath().contains("block"))) ;

        for (int i = 0; i < builder.subItems.size(); i++) {
            int finalI = i;
            if (builder.existingItems.stream().noneMatch(item -> item.getRegistryName().getPath().contains(builder.subItems.get(finalI).name().toLowerCase()))) {
                switch (builder.subItems.get(i)) {
                    case ORE:
                    case BLOCK:
                        break;
                    default:
                        items.add(ItemRegistry.register(name + "_" + builder.subItems.get(i).name().toLowerCase(), () -> new SubItemGenerated(builder::build, builder.subItems.get(finalI))));
                        break;
                }
            }
        }

        MaterialRegistryObject material = new MaterialRegistryObject(name, builder::build, items, blocks.size() > 0 ? blocks : null, fluid);
        materials.put(name, material);
        return material;
    }

    public void register(IEventBus bus) {
        Polaris.LOGGER.debug("Register");
        itemRegister.register(bus);
        blockRegister.register(bus);
    }
}
